export const btnValues = [
  { value: "2nd", extended: "true" },
  { value: "rad", extended: "true" },
  { value: "sin", extended: "true" },
  { value: "cos", extended: "true" },
  { value: "tan", extended: "true" },
  { value: "^", extended: "true" },
  { value: "lg", extended: "true" },
  { value: "In", extended: "true" },
  { value: "(", extended: "true" },
  { value: ")", extended: "true" },
  { value: "square-root-variable", extended: "true" },
  { value: "erase", isunary: "true" },
  { value: "backspace" },
  { value: "%" },
  { value: "/" },
  { value: "X!", extended: "true" },
  { value: "7" },
  { value: "8" },
  { value: "9" },
  { value: "*" },
  { value: "1/x", extended: "true" },
  { value: "4" },
  { value: "5" },
  { value: "6" },
  { value: "-", isunary: "true" },
  { value: "π", extended: "true" },
  { value: "1" },
  { value: "2" },
  { value: "3" },
  { value: "+" },
  { value: "showExtended" },
  { value: "e", extended: "true" },
  { value: "0" },
  { value: ".", isunary: "true" },
  { value: "=" },
];
