export const btnValues = [
  { value: "erase", isunary: 'true' },
  { value: "backspace" },
  { value: '^' },
  { value: "/" },
  { value: "7",},
  { value: "8",},
  { value: "9",},
  { value: "*" },
  { value: "4",},
  { value: "5",},
  { value: "6",},
  { value: "-", isunary: 'true' },
  { value: "1",},
  { value: "2",},
  { value: "3",},
  { value: "+" },
  { value: "more" },
  { value: "0",},
  { value: ".", isunary: 'true'},
  { value: "=" },
];
