export const buttonsContent = [
  { value: "C", priority: "16", unary: true },
  { value: "del", priority: "15", unary: true },
  { value: '^', priority: "14" },
  { value: "/", priority: "13" },
  { value: "7",},
  { value: "8",},
  { value: "9",},
  { value: "*", priority: "13" },
  { value: "4",},
  { value: "5",},
  { value: "6",},
  { value: "-", priority: "12", unary: true },
  { value: "1",},
  { value: "2",},
  { value: "3",},
  { value: "+", priority: "12" },
  { value: "more", priority: "15" },
  { value: "0",},
  { value: ",", priority: "15"},
  { value: "=", priority: "10" },
];
