export const interfaceContent = [
  { value: "C", priority: "", unary: true },
  { value: "<-", priority: "", unary: true },
  { value: "%", priority: "" },
  { value: "/", priority: "" },
  { value: "7",},
  { value: "8",},
  { value: "9",},
  { value: "*", priority: "" },
  { value: "4",},
  { value: "5",},
  { value: "6",},
  { value: "-", priority: "", unary: true },
  { value: "1",},
  { value: "2",},
  { value: "3",},
  { value: "+", priority: "" },
  { value: "?", priority: "" },
  { value: "0",},
  { value: ".", priority: ""},
  { value: "=", priority: "" },
];
